apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-info
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: k8s-info
            port: 
              number: 8080